[leveldb2]
enabled = true
dir = "./data/seaweedfs/filerldb2"

# Webhook notification for file events
[notification.webhook]
enabled = true
url = "http://localhost:8000/webhook/seaweed"
bearer_token = ""
queue_size = 100
