[leveldb2]
enabled = true
dir = "/Users/shivanshdarshan/Documents/Profession/DCC/lexical_search_prod/document-search/data/seaweedfs/filerldb2"

[notification.webhook]
enabled = true
url = "http://localhost:8000/webhook/seaweed"
bearer_token = ""
queue_size = 100
